# yaml file new 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas.default }}
  selector:
    matchLabels:
      name: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        name: {{ .Values.fullname }}
    containers:
    - image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
      name: {{ .Values.name }}
